title: RHS Japan Club
email: roswelljapan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roswell High's Japan Club is an activity-based club that explores
  Japan's cultural background through crafts, cuisine, and public media.
baseurl: ""
url: "https://rhsjapan.com"

markdown: kramdown
