include: ["_pages"]
title: RHS Japan Club
email: roswelljapan@gmail.com
description: >
  Roswell High's Japan Club is an activity-based club that explores
  Japan's cultural background through crafts, cuisine, and public media.
short: Immerse yourself in Japanese culture
permalink: "/:title/"
baseurl: ""
url: "https://rhsjapan.com"
cdn: "https://cdn.rhsjapan.com"
timezone: America/New_York
markdown: kramdown
