# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RHS Japan Club
email: roswelljapan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roswell High's Japan Club is an activity-based club that explores
  Japan's cultural background through crafts, cuisine, and public media.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rhsjapan.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
